# -*- coding: utf-8 -*-
"""Frame_Extraction_Codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ik2JNgrtDercp3idw9_sI4yqwKrbAzoj

# **Important Libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install opencv-python

"""# **Video Uploadation**"""

from google.colab import files

uploaded = files.upload()

"""# **Output after processing**"""

import os

output_folder_name = "extracted_frames"
os.makedirs(output_folder_name, exist_ok=True)
print(f"Folder '{output_folder_name}' created successfully.")

"""# **Extraction to frames**"""

import cv2

video_filename = list(uploaded.keys())[0]

cap = cv2.VideoCapture(video_filename)

if not cap.isOpened():
    print("Error: Could not open video.")
else:
    frame_count = 0
    while cap.isOpened():

        ret, frame = cap.read()

        if ret:
            frame_count += 1
        else:
            break

    cap.release()
    print(f"Finished reading {frame_count} frames.")

"""# **Save file**"""

import cv2
import os

cap = cv2.VideoCapture(video_filename)
if not cap.isOpened():
    print("Error: Could not open video.")
else:
    frame_count = 0
    while cap.isOpened():
        ret, frame = cap.read()

        if ret:
            output_path = os.path.join(output_folder_name, f"frame_{frame_count:04d}.png")
            cv2.imwrite(output_path, frame)

            frame_count += 1
        else:
            break


    cap.release()

    print(f"Saved {frame_count} frames to '{output_folder_name}'.")

"""# **Download Extracts**"""

import shutil
from google.colab import files

shutil.make_archive(output_folder_name, 'zip', output_folder_name)

files.download(f'{output_folder_name}.zip')

"""# **Delete Extracted Files**"""

import os
import shutil

if os.path.exists(output_folder_name):
    shutil.rmtree(output_folder_name)
    print(f"Removed folder: {output_folder_name}")


zip_file_name = f'{output_folder_name}.zip'
if os.path.exists(zip_file_name):
    os.remove(zip_file_name)
    print(f"Removed file: {zip_file_name}")



if os.path.exists(video_filename):
    os.remove(video_filename)
    print(f"Removed uploaded file: {video_filename}")