# -*- coding: utf-8 -*-
"""Python_Loops_Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRXjtdK38aoSn4jp1BibKsdCVR_7bJtO
"""



"""## Loops (51–150)

### 51. Print numbers from 1 to 100.
"""

# Loop from 1 to 100 (inclusive)
for i in range(1, 101):
    print(i)

"""### 52. Print even numbers from 1 to 100."""

# Loop from 2 to 100, incrementing by 2 to get even numbers
for i in range(2, 101, 2):
    print(i)

"""### 53. Print odd numbers from 1 to 100."""

# Loop from 1 to 100, incrementing by 2 to get odd numbers
for i in range(1, 101, 2):
    print(i)

"""### 54. Print multiples of 5 from 1 to 100."""

# Loop from 5 to 100, incrementing by 5 to get multiples of 5
for i in range(5, 101, 5):
    print(i)

"""### 55. Print table of a number."""

# Get input number from the user
num = int(input("Enter a number to print its multiplication table: "))

print(f"Multiplication Table for {num}:")
# Loop from 1 to 10 to generate table entries
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""### 56. Print all prime numbers between two numbers."""

# Get the lower and upper bounds from the user
lower = int(input("Enter lower bound of the interval: "))
upper = int(input("Enter upper bound of the interval: "))

print(f"Prime numbers between {lower} and {upper} are:")
# Iterate through each number in the interval
for num in range(lower, upper + 1):
    # Prime numbers are greater than 1
    if num > 1:
        is_prime = True
        # Check for factors from 2 up to the square root of the number
        for i in range(2, int(num**0.5) + 1):
            if (num % i) == 0:
                is_prime = False
                break
        if is_prime:
            print(num)

"""### 57. Print sum of first N natural numbers."""

# Get the value of N from the user
N = int(input("Enter a positive integer N: "))

# Method 1: Using a loop
sum_loop = 0
for i in range(1, N + 1):
    sum_loop += i
print(f"Method 1 (Loop): Sum of first {N} natural numbers is {sum_loop}")

# Method 2: Using the formula n*(n+1)/2
sum_formula = N * (N + 1) // 2
print(f"Method 2 (Formula): Sum of first {N} natural numbers is {sum_formula}")

"""### 58. Print factorial of a number."""

# Get the number from the user
num = int(input("Enter a non-negative integer: "))

# Method 1: Using a loop
if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("Method 1 (Loop): The factorial of 0 is 1.")
else:
    factorial_loop = 1
    for i in range(1, num + 1):
        factorial_loop *= i
    print(f"Method 1 (Loop): The factorial of {num} is {factorial_loop}.")

# Method 2: Using math.factorial function
import math
if num < 0:
    # Already handled above, but for completeness in this method context
    pass
elif num == 0:
    print("Method 2 (math.factorial): The factorial of 0 is 1.")
else:
    factorial_math = math.factorial(num)
    print(f"Method 2 (math.factorial): The factorial of {num} is {factorial_math}.")

"""### 59. Print Fibonacci series up to N terms."""

# Get the number of terms from the user
n_terms = int(input("Enter the number of terms for Fibonacci series: "))

# Initialize the first two terms
a, b = 0, 1
count = 0

if n_terms <= 0:
    print("Please enter a positive integer.")
elif n_terms == 1:
    print("Fibonacci series up to 1 term:")
    print(a)
else:
    print("Fibonacci series:")
    while count < n_terms:
        print(a, end=" ") # Print the current term
        nth = a + b      # Calculate the next term
        a = b            # Update 'a' to the current 'b'
        b = nth          # Update 'b' to the newly calculated next term
        count += 1
    print()

"""### 60. Print reverse Fibonacci series."""

# Get the number of terms for Fibonacci series
n_terms = int(input("Enter the number of terms for reverse Fibonacci series: "))

if n_terms <= 0:
    print("Please enter a positive integer.")
elif n_terms == 1:
    print("Reverse Fibonacci series up to 1 term:")
    print(0)
else:
    # Generate the Fibonacci series up to N terms
    fib_series = [0, 1]
    while len(fib_series) < n_terms:
        fib_series.append(fib_series[-1] + fib_series[-2])

    # Print the series in reverse order
    print("Reverse Fibonacci series:")
    for i in range(len(fib_series) - 1, -1, -1):
        print(fib_series[i], end=" ")
    print()