# -*- coding: utf-8 -*-
"""Python_Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8_3pbb9pSAy1Nyu-0IyMD_TAJA7q09L

# Dictionary
Generate Python code to demonstrate various dictionary manipulations, including creating a dictionary, accessing, adding, deleting, and updating key-value pairs, printing keys, values, and key-value pairs, checking for key existence, and counting element frequencies using a dictionary.

## Create Dictionary

### Subtask:
Generate Python code to create a simple dictionary with key-value pairs.

**Reasoning**:
The subtask requires generating Python code to create a dictionary. I will define a dictionary with several key-value pairs and then print it as instructed.
"""

my_dict = {
    "name": "Alice",
    "age": 30,
    "is_student": False,
    "courses": ["Math", "Science"]
}

print(my_dict)

"""## Access Value Using Key

### Subtask:
Generate Python code to access the value associated with a specific key in a dictionary.

**Reasoning**:
I will generate Python code to access specific values from the `my_dict` dictionary using their respective keys and then print these values as instructed.
"""

name_value = my_dict['name']
age_value = my_dict['age']

print(f"Name: {name_value}")
print(f"Age: {age_value}")

"""## Add New Key-Value Pair

### Subtask:
Generate Python code to add a new key-value pair to an existing dictionary.

**Reasoning**:
The subtask requires adding a new key-value pair to the existing `my_dict` and then printing the updated dictionary. I will use direct assignment to add the new key-value pair and then a print statement to display the dictionary.
"""

my_dict['city'] = 'New York'

print(my_dict)

"""## Update an Existing Key-Value Pair

### Subtask:
Generate Python code to update the value associated with an existing key in a dictionary.

## Update an Existing Key-Value Pair

### Subtask:
Generate Python code to update the value associated with an existing key in a dictionary.

**Reasoning**:
I will generate Python code to update the value associated with an existing key, 'age', in the `my_dict` dictionary and then print the dictionary to show the updated value.
"""

my_dict['age'] = 31

print(my_dict)

"""## Delete Key-Value Pair

### Subtask:
Generate Python code to delete a specific key-value pair from a dictionary.

## Delete Key-Value Pair

### Subtask:
Generate Python code to delete a specific key-value pair from a dictionary.

**Reasoning**:
I will generate Python code to delete the 'city' key-value pair from the `my_dict` dictionary using the `del` keyword and then print the updated dictionary.
"""

del my_dict['city']

print(my_dict)

"""## Print Keys, Values, and Key-Value Pairs

### Subtask:
Generate Python code to print all keys, all values, and all key-value pairs from a dictionary.

**Reasoning**:
The previous subtask of deleting a key-value pair has been completed. The next logical step in dictionary manipulation is to print keys, values, and key-value pairs. I will now generate Python code to print all keys, all values, and all key-value pairs from the `my_dict` dictionary.
"""

print("Keys:", my_dict.keys())
print("Values:", my_dict.values())
print("Items:", my_dict.items())

"""## Check for Key Existence

### Subtask:
Generate Python code to check if a specific key exists in a dictionary.

**Reasoning**:
The previous subtask of printing dictionary elements has been completed. The next logical step in dictionary manipulation is to check for key existence. I will now generate Python code to check for the existence of specific keys in the `my_dict` dictionary and print the results.
"""

print("'name' exists in my_dict?:", 'name' in my_dict)
print("'city' exists in my_dict?:", 'city' in my_dict)

"""## Count Element Frequencies Using a Dictionary

### Subtask:
Generate Python code to count the frequency of elements in a list using a dictionary.

## Count Element Frequencies Using a Dictionary

### Subtask:
Generate Python code to count the frequency of elements in a list using a dictionary.

**Reasoning**:
The previous subtask of introducing how to count element frequencies has been completed. Now, I will generate Python code to demonstrate counting element frequencies in a list using a dictionary.
"""

my_list_to_count = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']

frequency_dict = {}
for item in my_list_to_count:
    frequency_dict[item] = frequency_dict.get(item, 0) + 1

print("Original List:", my_list_to_count)
print("Element Frequencies:", frequency_dict)

"""## Final Task

### Subtask:
Summarize the generated code snippets and their functionalities for dictionary manipulations.

## Summary:

### Data Analysis Key Findings

*   **Dictionary Creation**: A dictionary `my_dict` was successfully created with initial key-value pairs including `"name": "Alice"`, `"age": 30`, `"is_student": False`, and `"courses": ["Math", "Science"]`.
*   **Accessing Values**: Values were successfully accessed using keys, specifically retrieving "Alice" for 'name' and 30 for 'age'.
*   **Adding Key-Value Pair**: A new key-value pair, `'city': 'New York'`, was successfully added to `my_dict`.
*   **Updating Key-Value Pair**: The value for the 'age' key was successfully updated from 30 to 31.
*   **Deleting Key-Value Pair**: The key-value pair for 'city' was successfully deleted from `my_dict`.
*   **Printing Dictionary Components**: The `.keys()`, `.values()`, and `.items()` methods correctly extracted and displayed the keys, values, and key-value pairs of the dictionary, respectively.
*   **Checking Key Existence**: The `'name' in my_dict` check returned `True`, while `'city' in my_dict` returned `False`, accurately reflecting the dictionary's state after deletion.
*   **Counting Element Frequencies**: A frequency dictionary `{'apple': 3, 'banana': 2, 'orange': 1}` was successfully generated from the list `['apple', 'banana', 'apple', 'orange', 'banana', 'apple']`.

### Insights or Next Steps

*   The demonstrated dictionary manipulations cover essential operations for data management and processing in Python, highlighting dictionaries as versatile and efficient data structures.
*   Future analysis could involve applying these dictionary manipulation techniques to real-world datasets, such as processing configuration files, managing user profiles, or aggregating categorical data.
"""