# -*- coding: utf-8 -*-
"""Python_Basic_codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRXjtdK38aoSn4jp1BibKsdCVR_7bJtO
"""



"""## Basic Input/Output (1–50)

### 1. Write a program to print “Hello World”.
"""

print("Hello World")

"""### 2. Write a program to input two numbers and print their sum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("The sum is:", num1 + num2)

"""### 3. Input a number and print whether it is positive or negative."""

num = float(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

"""### 4. Input a number and print its square."""

num = float(input("Enter a number: "))
print("The square is:", num ** 2)

"""### 5. Input two numbers and print the larger one."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("The larger number is:", max(num1, num2))

"""### 6. Input name and age and print them."""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Name:", name, ", Age:", age)

"""### 7. Input three numbers and print the greatest."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
print("The greatest number is:", max(num1, num2, num3))

"""### 8. Input temperature in Celsius and convert to Fahrenheit."""

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

"""### 9. Input a number and print if it is even or odd."""

num = int(input("Enter an integer: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

"""### 10. Input a number and print its cube."""

num = float(input("Enter a number: "))
print("The cube is:", num ** 3)

"""### 11. Input two numbers and print their average."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("The average is:", (num1 + num2) / 2)

"""### 12. Input a number and print its absolute value."""

num = float(input("Enter a number: "))
print("The absolute value is:", abs(num))

"""### 13. Input a float and print it rounded to 2 decimals."""

num = float(input("Enter a float number: "))
print("Rounded to 2 decimals:", round(num, 2))

"""### 14. Input a number and print the last digit."""

num = int(input("Enter an integer: "))
print("The last digit is:", abs(num) % 10)

"""### 15. Input a number and print the first digit."""

num = int(input("Enter an integer: "))
num_str = str(abs(num))
if num_str:
    print("The first digit is:", num_str[0])
else:
    print("No digits entered.")

"""### 16. Input a number and print sum of first and last digit."""

num = int(input("Enter an integer: "))
num_abs = abs(num)
last_digit = num_abs % 10
num_str = str(num_abs)
if num_str:
    first_digit = int(num_str[0])
    print("Sum of first and last digit is:", first_digit + last_digit)
else:
    print("No digits entered.")

"""### 17. Input a number and print number of digits."""

num = int(input("Enter an integer: "))
print("Number of digits:", len(str(abs(num))))

"""### 18. Input a number and print reverse of the number."""

num = input("Enter a number: ")
print("Reversed number:", num[::-1])

"""### 43. Input marks of 5 subjects; print percentage."""

sub1 = float(input("Enter marks for subject 1: "))
sub2 = float(input("Enter marks for subject 2: "))
sub3 = float(input("Enter marks for subject 3: "))
sub4 = float(input("Enter marks for subject 4: "))
sub5 = float(input("Enter marks for subject 5: "))



total_marks = sub1 + sub2 + sub3 + sub4 + sub5
percentage = (total_marks / 500) * 100 # Assuming max marks for each subject is 100

print(f"Total Marks: {total_marks}")
print(f"Percentage: {percentage:.2f}%")

"""### 44. Input number; print table."""

num = int(input("Enter a number to print its multiplication table: "))

print(f"Multiplication Table for {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""### 45. Input any two numbers; print maximum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The maximum number is:", max(num1, num2))

"""### 46. Input two numbers; print minimum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The minimum number is:", min(num1, num2))

"""### 47. Input a letter; check if it is a vowel or consonant."""

char = input("Enter a letter: ").lower()

if len(char) == 1 and char.isalpha():
    if char in ('a', 'e', 'i', 'o', 'u'):
        print(f"'{char}' is a vowel.")
    else:
        print(f"'{char}' is a consonant.")
else:
    print("Please enter a single letter.")

"""### 48. Input number; print factorial."""

import math

num = int(input("Enter a non-negative integer: "))

if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    factorial = math.factorial(num)
    print(f"The factorial of {num} is {factorial}.")

"""### 49. Input number of terms; print Fibonacci series."""

n_terms = int(input("Enter the number of terms for Fibonacci series: "))

a, b = 0, 1
count = 0

if n_terms <= 0:
    print("Please enter a positive integer.")
elif n_terms == 1:
    print("Fibonacci series up to 1 term:")
    print(a)
else:
    print("Fibonacci series:")
    while count < n_terms:
        print(a, end=" ")
        nth = a + b
        a = b
        b = nth
        count += 1
    print()

"""### 50. Input number; check if prime or not."""

num = int(input("Enter a number: "))

if num <= 1:
    print(f"{num} is not a prime number.")
elif num == 2:
    print(f"{num} is a prime number.")
else:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")

"""### 43. Input marks of 5 subjects; print percentage."""

sub1 = float(input("Enter marks for subject 1: "))
sub2 = float(input("Enter marks for subject 2: "))
sub3 = float(input("Enter marks for subject 3: "))
sub4 = float(input("Enter marks for subject 4: "))
sub5 = float(input("Enter marks for subject 5: "))

total_marks = sub1 + sub2 + sub3 + sub4 + sub5
percentage = (total_marks / 500) * 100 # Assuming max marks for each subject is 100

print(f"Total Marks: {total_marks}")
print(f"Percentage: {percentage:.2f}%")

"""### 44. Input number; print table."""

num = int(input("Enter a number to print its multiplication table: "))

print(f"Multiplication Table for {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""### 45. Input any two numbers; print maximum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The maximum number is:", max(num1, num2))

"""### 46. Input two numbers; print minimum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The minimum number is:", min(num1, num2))

"""### 47. Input a letter; check if it is a vowel or consonant."""

char = input("Enter a letter: ").lower()

if len(char) == 1 and char.isalpha():
    if char in ('a', 'e', 'i', 'o', 'u'):
        print(f"'{char}' is a vowel.")
    else:
        print(f"'{char}' is a consonant.")
else:
    print("Please enter a single letter.")

"""### 48. Input number; print factorial."""

import math

num = int(input("Enter a non-negative integer: "))

if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    factorial = math.factorial(num)
    print(f"The factorial of {num} is {factorial}.")

"""### 49. Input number of terms; print Fibonacci series."""

n_terms = int(input("Enter the number of terms for Fibonacci series: "))

a, b = 0, 1
count = 0

if n_terms <= 0:
    print("Please enter a positive integer.")
elif n_terms == 1:
    print("Fibonacci series up to 1 term:")
    print(a)
else:
    print("Fibonacci series:")
    while count < n_terms:
        print(a, end=" ")
        nth = a + b
        a = b
        b = nth
        count += 1
    print()

"""### 50. Input number; check if prime or not."""

num = int(input("Enter a number: "))

if num <= 1:
    print(f"{num} is not a prime number.")
elif num == 2:
    print(f"{num} is a prime number.")
else:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")

"""### 43. Input marks of 5 subjects; print percentage."""

sub1 = float(input("Enter marks for subject 1: "))
sub2 = float(input("Enter marks for subject 2: "))
sub3 = float(input("Enter marks for subject 3: "))
sub4 = float(input("Enter marks for subject 4: "))
sub5 = float(input("Enter marks for subject 5: "))

total_marks = sub1 + sub2 + sub3 + sub4 + sub5
percentage = (total_marks / 500) * 100 # Assuming max marks for each subject is 100

print(f"Total Marks: {total_marks}")
print(f"Percentage: {percentage:.2f}%")

"""### 44. Input number; print table."""

num = int(input("Enter a number to print its multiplication table: "))

print(f"Multiplication Table for {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""### 45. Input any two numbers; print maximum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The maximum number is:", max(num1, num2))

"""### 46. Input two numbers; print minimum."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("The minimum number is:", min(num1, num2))

"""### 47. Input a letter; check if it is a vowel or consonant."""

char = input("Enter a letter: ").lower()

if len(char) == 1 and char.isalpha():
    if char in ('a', 'e', 'i', 'o', 'u'):
        print(f"'{char}' is a vowel.")
    else:
        print(f"'{char}' is a consonant.")
else:
    print("Please enter a single letter.")

"""### 48. Input number; print factorial."""

import math

num = int(input("Enter a non-negative integer: "))

if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    factorial = math.factorial(num)
    print(f"The factorial of {num} is {factorial}.")

"""### 49. Input number of terms; print Fibonacci series."""

n_terms = int(input("Enter the number of terms for Fibonacci series: "))

a, b = 0, 1
count = 0

if n_terms <= 0:
    print("Please enter a positive integer.")
elif n_terms == 1:
    print("Fibonacci series up to 1 term:")
    print(a)
else:
    print("Fibonacci series:")
    while count < n_terms:
        print(a, end=" ")
        nth = a + b
        a = b
        b = nth
        count += 1
    print()

"""### 50. Input number; check if prime or not."""

num = int(input("Enter a number: "))

if num <= 1:
    print(f"{num} is not a prime number.")
elif num == 2:
    print(f"{num} is a prime number.")
else:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")

"""### 19. Input age; print if eligible to vote."""

age = int(input("Enter your age: "))
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

"""### 20. Input speed; check if speed > 60 print “Overspeeding”."""

speed = float(input("Enter speed: "))
if speed > 60:
    print("Overspeeding")

"""### 21. Input salary and bonus; print total salary."""

salary = float(input("Enter salary: "))
bonus = float(input("Enter bonus: "))
total_salary = salary + bonus
print("Total Salary:", total_salary)

"""### 22. Input length & breadth; print area of rectangle."""

length = float(input("Enter length: "))
breadth = float(input("Enter breadth: "))
area = length * breadth
print("Area of rectangle:", area)

"""### 23. Input radius; print circumference of a circle."""

import math
radius = float(input("Enter radius: "))
circumference = 2 * math.pi * radius
print("Circumference of circle:", circumference)

"""### 24. Input radius; print volume of sphere."""

import math
radius = float(input("Enter radius: "))
volume = (4/3) * math.pi * (radius ** 3)
print("Volume of sphere:", volume)

"""### 25. Input two numbers; swap them."""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("Before swap: num1 =", num1, ", num2 =", num2)
num1, num2 = num2, num1
print("After swap: num1 =", num1, ", num2 =", num2)

"""### 26. Input two strings; print them in reverse order."""

str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
print("Strings in reverse order:", str2, str1)

"""### 27. Input two numbers; print quotient & remainder."""

num1 = int(input("Enter dividend: "))
num2 = int(input("Enter divisor: "))
quotient = num1 // num2
remainder = num1 % num2
print("Quotient:", quotient, ", Remainder:", remainder)

"""### 28. Input marks; print pass or fail."""

marks = float(input("Enter marks (0-100): "))
if marks >= 40:
    print("Pass")
else:
    print("Fail")

"""### 29. Input days; convert to weeks and days."""

total_days = int(input("Enter total days: "))
weeks = total_days // 7
remaining_days = total_days % 7
print(f"{total_days} days is equal to {weeks} weeks and {remaining_days} days.")

"""### 30. Input minutes; convert to hours."""

minutes = float(input("Enter minutes: "))
hours = minutes / 60
print(f"{minutes} minutes is equal to {hours:.2f} hours.")

"""### 31. Input hours; convert to minutes."""

hours = float(input("Enter hours: "))
minutes = hours * 60
print(f"{hours} hours is equal to {minutes:.2f} minutes.")

"""### 32. Input distance (km); convert to meters."""

km = float(input("Enter distance in kilometers: "))
meters = km * 1000
print(f"{km} km is equal to {meters:.0f} meters.")

"""### 33. Input seconds; convert to h/m/s."""

total_seconds = int(input("Enter total seconds: "))
hours = total_seconds // 3600
remaining_seconds = total_seconds % 3600
minutes = remaining_seconds // 60
seconds = remaining_seconds % 60
print(f"{total_seconds} seconds is equal to {hours} hours, {minutes} minutes, and {seconds} seconds.")

"""### 34. Input number; check multiple of 5."""

num = int(input("Enter an integer: "))
if num % 5 == 0:
    print(f"{num} is a multiple of 5.")
else:
    print(f"{num} is not a multiple of 5.")

"""### 35. Input number; check multiple of 3 and 7."""

num = int(input("Enter an integer: "))
if num % 3 == 0 and num % 7 == 0:
    print(f"{num} is a multiple of both 3 and 7.")
else:
    print(f"{num} is not a multiple of both 3 and 7.")

"""### 36. Input marks (0-100); print grade."""

marks = float(input("Enter marks (0-100): "))
if 90 <= marks <= 100:
    print("Grade: A")
elif 80 <= marks < 90:
    print("Grade: B")
elif 70 <= marks < 80:
    print("Grade: C")
elif 60 <= marks < 70:
    print("Grade: D")
elif 0 <= marks < 60:
    print("Grade: F")
else:
    print("Invalid marks")

"""### 37. Input two numbers; print power (a^b)."""

base = float(input("Enter the base number: "))
exponent = float(input("Enter the exponent: "))
result = base ** exponent
print(f"{base} to the power of {exponent} is: {result}")

"""### 38. Input character; print ASCII value."""

char = input("Enter a character: ")
if len(char) == 1:
    print(f"The ASCII value of '{char}' is: {ord(char)}")
else:
    print("Please enter only one character.")

"""### 39. Input number; check divisible by 9."""

num = int(input("Enter an integer: "))
if num % 9 == 0:
    print(f"{num} is divisible by 9.")
else:
    print(f"{num} is not divisible by 9.")

"""### 40. Input year; check leap year."""

year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

"""### 41. Input 3 angles; check if triangle is valid."""

angle1 = float(input("Enter first angle: "))
angle2 = float(input("Enter second angle: "))
angle3 = float(input("Enter third angle: "))
if angle1 > 0 and angle2 > 0 and angle3 > 0 and (angle1 + angle2 + angle3) == 180:
    print("The angles form a valid triangle.")
else:
    print("The angles do not form a valid triangle.")

"""### 42. Input cost price & selling price; print profit/loss."""

cost_price = float(input("Enter cost price: "))
selling_price = float(input("Enter selling price: "))

if selling_price > cost_price:
    profit = selling_price - cost_price
    print(f"Profit: {profit:.2f}")
elif selling_price < cost_price:
    loss = cost_price - selling_price
    print(f"Loss: {loss:.2f}")
else:
    print("No profit, no loss.")