# -*- coding: utf-8 -*-
"""Python_Strings_Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRXjtdK38aoSn4jp1BibKsdCVR_7bJtO

## Strings (151–250)

### 151. Count vowels in a string.
"""

# Method 1: Using a loop
def count_vowels_loop(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

# Method 2: Using sum() with a generator expression
def count_vowels_sum(s):
    vowels = "aeiouAEIOU"
    return sum(1 for char in s if char in vowels)

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): Number of vowels = {count_vowels_loop(input_string)}")
print(f"Method 2 (Sum): Number of vowels = {count_vowels_sum(input_string)}")

"""### 152. Count consonants in a string."""

# Method 1: Using a loop
def count_consonants_loop(s):
    vowels = "aeiouAEIOU"
    consonants_count = 0
    for char in s:
        if char.isalpha() and char not in vowels:
            consonants_count += 1
    return consonants_count

# Method 2: Using sum() with a generator expression
def count_consonants_sum(s):
    vowels = "aeiouAEIOU"
    return sum(1 for char in s if char.isalpha() and char not in vowels)

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): Number of consonants = {count_consonants_loop(input_string)}")
print(f"Method 2 (Sum): Number of consonants = {count_consonants_sum(input_string)}")

"""### 153. Count digits in a string."""

# Method 1: Using a loop and isdigit()
def count_digits_loop(s):
    digit_count = 0
    for char in s:
        if char.isdigit():
            digit_count += 1
    return digit_count

# Method 2: Using sum() with a generator expression
def count_digits_sum(s):
    return sum(1 for char in s if char.isdigit())

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): Number of digits = {count_digits_loop(input_string)}")
print(f"Method 2 (Sum): Number of digits = {count_digits_sum(input_string)}")

"""### 154. Count special characters."""

# Method 1: Using a loop and isalnum()
def count_special_chars_loop(s):
    special_char_count = 0
    for char in s:
        # A character is special if it's not alphanumeric and not a space
        if not char.isalnum() and not char.isspace():
            special_char_count += 1
    return special_char_count

# Method 2: Using sum() with a generator expression
def count_special_chars_sum(s):
    return sum(1 for char in s if not char.isalnum() and not char.isspace())

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): Number of special characters = {count_special_chars_loop(input_string)}")
print(f"Method 2 (Sum): Number of special characters = {count_special_chars_sum(input_string)}")

"""### 155. Convert to uppercase."""

# Method 1: Using upper() method
def convert_to_uppercase(s):
    return s.upper()

input_string = input("Enter a string: ")

print(f"Uppercase string: {convert_to_uppercase(input_string)}")

"""### 156. Convert to lowercase."""

# Method 1: Using lower() method
def convert_to_lowercase(s):
    return s.lower()

input_string = input("Enter a string: ")

print(f"Lowercase string: {convert_to_lowercase(input_string)}")

"""### 157. Toggle case of characters."""

# Method 1: Using swapcase() method
def toggle_case_swapcase(s):
    return s.swapcase()

# Method 2: Using a loop with islower(), isupper()
def toggle_case_loop(s):
    toggled_string = []
    for char in s:
        if char.islower():
            toggled_string.append(char.upper())
        elif char.isupper():
            toggled_string.append(char.lower())
        else:
            toggled_string.append(char)
    return "".join(toggled_string)

input_string = input("Enter a string: ")

print(f"Method 1 (swapcase): Toggled case string: {toggle_case_swapcase(input_string)}")
print(f"Method 2 (Loop): Toggled case string: {toggle_case_loop(input_string)}")

"""### 158. Reverse a string."""

# Method 1: Using slicing
def reverse_string_slicing(s):
    return s[::-1]

# Method 2: Using a loop
def reverse_string_loop(s):
    reversed_s = ""
    for char in s:
        reversed_s = char + reversed_s
    return reversed_s

# Method 3: Using reversed() function and join()
def reverse_string_reversed(s):
    return "".join(reversed(s))

input_string = input("Enter a string: ")

print(f"Method 1 (Slicing): Reversed string: {reverse_string_slicing(input_string)}")
print(f"Method 2 (Loop): Reversed string: {reverse_string_loop(input_string)}")
print(f"Method 3 (reversed): Reversed string: {reverse_string_reversed(input_string)}")

"""### 159. Check palindrome string."""

# Method 1: Using slicing
def is_palindrome_slicing(s):
    # Convert to lowercase and remove spaces for a more robust check
    cleaned_s = "".join(filter(str.isalnum, s)).lower()
    return cleaned_s == cleaned_s[::-1]

# Method 2: Using a loop
def is_palindrome_loop(s):
    cleaned_s = "".join(filter(str.isalnum, s)).lower()
    length = len(cleaned_s)
    for i in range(length // 2):
        if cleaned_s[i] != cleaned_s[length - 1 - i]:
            return False
    return True

input_string = input("Enter a string: ")

print(f"Method 1 (Slicing): Is '{input_string}' a palindrome? {is_palindrome_slicing(input_string)}")
print(f"Method 2 (Loop): Is '{input_string}' a palindrome? {is_palindrome_loop(input_string)}")

"""### 160. Check anagram strings."""

# Method 1: Using sorted() function
def are_anagrams_sorted(s1, s2):
    # Clean strings: remove spaces and convert to lowercase
    cleaned_s1 = "".join(filter(str.isalnum, s1)).lower()
    cleaned_s2 = "".join(filter(str.isalnum, s2)).lower()
    return sorted(cleaned_s1) == sorted(cleaned_s2)

# Method 2: Using character counts (frequency map)
from collections import Counter
def are_anagrams_counter(s1, s2):
    cleaned_s1 = "".join(filter(str.isalnum, s1)).lower()
    cleaned_s2 = "".join(filter(str.isalnum, s2)).lower()
    return Counter(cleaned_s1) == Counter(cleaned_s2)

string1 = input("Enter first string: ")
string2 = input("Enter second string: ")

print(f"Method 1 (Sorted): Are '{string1}' and '{string2}' anagrams? {are_anagrams_sorted(string1, string2)}")
print(f"Method 2 (Counter): Are '{string1}' and '{string2}' anagrams? {are_anagrams_counter(string1, string2)}")

"""### 161. Check if string contains only numbers."""

# Method 1: Using isdigit() method
def contains_only_numbers(s):
    return s.isdigit()

input_string = input("Enter a string: ")

print(f"Does '{input_string}' contain only numbers? {contains_only_numbers(input_string)}")

"""### 162. Check if string contains only alphabets."""

# Method 1: Using isalpha() method
def contains_only_alphabets(s):
    return s.isalpha()

input_string = input("Enter a string: ")

print(f"Does '{input_string}' contain only alphabets? {contains_only_alphabets(input_string)}")

"""### 163. Remove vowels from a string."""

# Method 1: Using a loop and join()
def remove_vowels_loop(s):
    vowels = "aeiouAEIOU"
    result = []
    for char in s:
        if char not in vowels:
            result.append(char)
    return "".join(result)

# Method 2: Using list comprehension and join()
def remove_vowels_comprehension(s):
    vowels = "aeiouAEIOU"
    return "".join([char for char in s if char not in vowels])

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): String without vowels: {remove_vowels_loop(input_string)}")
print(f"Method 2 (Comprehension): String without vowels: {remove_vowels_comprehension(input_string)}")

"""### 164. Remove spaces from a string."""

# Method 1: Using replace() method
def remove_spaces_replace(s):
    return s.replace(" ", "")

# Method 2: Using join() and split()
def remove_spaces_join_split(s):
    # split() without arguments splits by any whitespace and removes empty strings
    return "".join(s.split())

input_string = input("Enter a string: ")

print(f"Method 1 (replace): String without spaces: {remove_spaces_replace(input_string)}")
print(f"Method 2 (join/split): String without spaces: {remove_spaces_join_split(input_string)}")

"""### 165. Remove digits from a string."""

# Method 1: Using a loop and isdigit()
def remove_digits_loop(s):
    result = []
    for char in s:
        if not char.isdigit():
            result.append(char)
    return "".join(result)

# Method 2: Using list comprehension and join()
def remove_digits_comprehension(s):
    return "".join([char for char in s if not char.isdigit()])

input_string = input("Enter a string: ")

print(f"Method 1 (Loop): String without digits: {remove_digits_loop(input_string)}")
print(f"Method 2 (Comprehension): String without digits: {remove_digits_comprehension(input_string)}")

"""### 166. Remove special characters."""

# Method 1: Using isalnum() and join()
def remove_special_chars_isalnum(s):
    result = []
    for char in s:
        if char.isalnum() or char.isspace(): # Keep alphanumeric and spaces
            result.append(char)
    return "".join(result)

# Method 2: Using regular expressions
import re
def remove_special_chars_regex(s):
    # Keep alphanumeric characters and spaces
    return re.sub(r'[^a-zA-Z0-9\s]', '', s)

input_string = input("Enter a string: ")

print(f"Method 1 (isalnum): String without special characters: {remove_special_chars_isalnum(input_string)}")
print(f"Method 2 (Regex): String without special characters: {remove_special_chars_regex(input_string)}")

"""### 167. Replace spaces with dashes."""

# Method 1: Using replace() method
def replace_spaces_with_dashes(s):
    return s.replace(" ", "-")

input_string = input("Enter a string: ")

print(f"String with spaces replaced by dashes: {replace_spaces_with_dashes(input_string)}")

"""### 168. Count frequency of each character."""

# Method 1: Using a dictionary and a loop
def char_frequency_loop(s):
    frequency = {}
    for char in s:
        frequency[char] = frequency.get(char, 0) + 1
    return frequency

# Method 2: Using collections.Counter
from collections import Counter
def char_frequency_counter(s):
    return Counter(s)

input_string = input("Enter a string: ")

print("Method 1 (Loop) - Character frequencies:")
for char, count in char_frequency_loop(input_string).items():
    print(f"'{char}': {count}")

print("\nMethod 2 (Counter) - Character frequencies:")
for char, count in char_frequency_counter(input_string).items():
    print(f"'{char}': {count}")

"""### 169. Find most repeated character."""

# Method 1: Using collections.Counter
from collections import Counter
def most_repeated_char_counter(s):
    if not s: # Handle empty string case
        return None
    # Filter out spaces if they shouldn't be considered
    s_filtered = s.replace(' ', '')
    if not s_filtered:
        return None
    counts = Counter(s_filtered)
    return counts.most_common(1)[0][0] # Returns the character of the most common item

# Method 2: Manual loop with dictionary
def most_repeated_char_loop(s):
    if not s: # Handle empty string case
        return None
    s_filtered = s.replace(' ', '')
    if not s_filtered:
        return None

    frequency = {}
    for char in s_filtered:
        frequency[char] = frequency.get(char, 0) + 1

    if not frequency: # If string only contained spaces or was empty after filtering
        return None

    max_count = 0
    most_char = ''
    for char, count in frequency.items():
        if count > max_count:
            max_count = count
            most_char = char
    return most_char

input_string = input("Enter a string: ")

print(f"Method 1 (Counter): Most repeated character: {most_repeated_char_counter(input_string)}")
print(f"Method 2 (Loop): Most repeated character: {most_repeated_char_loop(input_string)}")

"""### 170. Find least repeated character."""

# Method 1: Using collections.Counter
from collections import Counter
def least_repeated_char_counter(s):
    if not s: # Handle empty string case
        return None
    s_filtered = s.replace(' ', '') # Filter out spaces if they shouldn't be considered
    if not s_filtered:
        return None
    counts = Counter(s_filtered)
    # most_common(N) returns N most common elements. To get least, we can sort by count ascending.
    # Note: If multiple characters have the same minimum count, this returns one of them.
    return sorted(counts.items(), key=lambda item: item[1])[0][0]

# Method 2: Manual loop with dictionary
def least_repeated_char_loop(s):
    if not s: # Handle empty string case
        return None
    s_filtered = s.replace(' ', '')
    if not s_filtered:
        return None

    frequency = {}
    for char in s_filtered:
        frequency[char] = frequency.get(char, 0) + 1

    if not frequency: # If string only contained spaces or was empty after filtering
        return None

    min_count = float('inf')
    least_char = ''
    for char, count in frequency.items():
        if count < min_count:
            min_count = count
            least_char = char
    return least_char

input_string = input("Enter a string: ")

print(f"Method 1 (Counter): Least repeated character: {least_repeated_char_counter(input_string)}")
print(f"Method 2 (Loop): Least repeated character: {least_repeated_char_loop(input_string)}")

"""### 171. Count words in a string."""

# Method 1: Using split()
def count_words_split(s):
    # split() without arguments handles multiple spaces and leading/trailing spaces
    words = s.split()
    return len(words)

input_string = input("Enter a string: ")

print(f"Number of words: {count_words_split(input_string)}")

"""### 172. Reverse each word in a string."""

# Method 1: Using split(), slicing, and join()
def reverse_each_word(s):
    words = s.split()
    reversed_words = [word[::-1] for word in words]
    return " ".join(reversed_words)

input_string = input("Enter a string: ")

print(f"String with each word reversed: {reverse_each_word(input_string)}")

"""### 173. Reverse word order."""

# Method 1: Using split(), reversed(), and join()
def reverse_word_order(s):
    words = s.split()
    reversed_words = list(reversed(words))
    return " ".join(reversed_words)

# Method 2: Using split() and slicing
def reverse_word_order_slicing(s):
    words = s.split()
    return " ".join(words[::-1])

input_string = input("Enter a string: ")

print(f"Method 1 (reversed): String with word order reversed: {reverse_word_order(input_string)}")
print(f"Method 2 (Slicing): String with word order reversed: {reverse_word_order_slicing(input_string)}")

"""### 174. Check if sentence contains substring."""

# Method 1: Using 'in' operator
def contains_substring(sentence, substring):
    return substring in sentence

input_sentence = input("Enter a sentence: ")
input_substring = input("Enter a substring to check for: ")

print(f"Does '{input_sentence}' contain '{input_substring}'? {contains_substring(input_sentence, input_substring)}")

"""### 175. Remove duplicates from string."""

# Method 1: Using a set (maintains order of first appearance)
def remove_duplicates_set_ordered(s):
    seen = set()
    result = []
    for char in s:
        if char not in seen:
            seen.add(char)
            result.append(char)
    return "".join(result)

# Method 2: Using a set and join (order not guaranteed for original string)
def remove_duplicates_set_unordered(s):
    return "".join(sorted(set(s), key=s.index)) # sorted with key=s.index to maintain order

input_string = input("Enter a string: ")

print(f"Method 1 (Set Ordered): String with duplicates removed: {remove_duplicates_set_ordered(input_string)}")
print(f"Method 2 (Set Unordered - with order): String with duplicates removed: {remove_duplicates_set_unordered(input_string)}")